from django.apps import AppConfig


# Vanillia-autogenerated content
class CatalogConfig(AppConfig):
    # The type of primary key to use for models in this application when no primary key is explicitly specified.
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'catalog'
